### ISSUE TITLE
generate publication list from master bib file with filter by option

### ISSUE THREAD

**Issue by shbonita** [SERESLab/SERESLab.github.io#4]
Instead of putting in citations directly, I would like to have them generated by a script given a bib file as input.  The output will be based on the style we specify and should be changeable on the fly.

Each publication can be filtered by type, venue, award, topic and year. Each also has an image associated with it. 

I have a bib file that has all these publications but the bib file does not have topic, award and image.  How do we add that in before generating the list of publications?

**Comment by TrNiTu** [comment]
https://citation.js.org/
https://faculty.washington.edu/ajko/

**Comment by shbonita** [comment]
I can provide you with the master bib file and metadata for each bib entry. 

The metadata will consist of a json file that is linked to the bib file via the ID (this is the first token after the first open curly brace right before the comma. for e.g., `@article{SharafiSGBBC20`,  In this case the ID is `SharafiSGBBC20`

The metadata file will have tag indicating topics that are relevant for that bib entry and also will provide a short blurb no more than 250 characters.

**Comment by shbonita** [comment]
Each publication should also be tagged with the tags under it.
